-- 1) What is the total revenue generated by the male vs. female customers ?

select gender, sum(purchase_amount) as revenue 
from my_table
group by gender;

-- 2) which customers used a discount but still spent more than the average purchase amount ?

SELECT 
    customer_id, 
    purchase_amount
FROM my_table
WHERE discount_applied = 'Yes' 
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM my_table);
  
  -- 3) Which are the top 5 products with highest average review rating ?
  
  SELECT 
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS `Average Product Rating`
FROM my_table
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- 4) Compare the average purchase amount between Standard and Express shipping ?

SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS `Average Purchase Amount`
FROM my_table
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- 5) Do subscribed customers spend more ? Compare average spend and total revenue between subscribers and non subscribers ?

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM my_table 
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- 6) Which 5 products have the highest percentage of purchases with discount applied ?

SELECT 
    item_purchased,
    ROUND(
        100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 
    2) AS discount_rate
FROM my_table
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;